djtest/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('kirara/', include('kirara.urls')),
    path('', admin.site.urls),
]

kirara/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('<int:pk>/',views.CharaDetailView.as_view(),name='chara_detail'),
    path('',views.CharaListView.as_view()),
]

kirara/models.py
from django.db import models

# Create your models here.
class Chara(models.Model,metaclass=models.base.ModelBase):
    name=models.CharField(max_length=20)
    hp=models.IntegerField()
    atk=models.IntegerField()
    matk=models.IntegerField()
    dif=models.IntegerField()
    mdif=models.IntegerField()
    spd=models.IntegerField()
    RARE_CHOICES=((3,3),(4,4),(5,5),)
    rare=models.IntegerField(choices=RARE_CHOICES,default=5)
    skill=models.IntegerField()
    JOB_CHOICES=((0,'戦士'),(1,'魔法使い'),(2,'ナイト'),
    (3,'僧侶'),(4,'アルケミスト'),)
    job=models.IntegerField(choices=JOB_CHOICES,default=1)
    
    def __init__(self,*args,**kwargs):
        models.Model.__init__(self,*args,**kwargs)
        self.nextBuf=0.0
        self.atkBuf=0.0
    def __str__(self):
        return self.name+str(self.rare)
    def calcAtk(self):
        return self.atk*self.skill*(1+self.nextBuf)*(1+self.atkBuf)/10000
    def calcMatk(self):
        return self.matk*self.skill*(1+self.nextBuf)*(1+self.atkBuf)/10000
    def calcDif(self):
        return self.dif*self.hp/10000
    def calcMdif(self):
        return self.mdif*self.hp/10000
    

kirara/views.py
from django.shortcuts import render
from django.views.generic import DetailView,ListView
from .models import Chara
# Create your views here.
class CharaListView(ListView):
    model=Chara

class CharaDetailView(DetailView):
    model=Chara

kirara/templates/kirara/chara_detail.html
<!DOCTYPE html>
<html>
    <head>
        <title>kirara test</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <h1>キャラクターステータス一覧</h1>
        <table border="1">
            <tr>
                <td>キャラ</td>
                <td>クラス</td>
                <td>HP</td>
                <td>ATK</td>
                <td>MAT</td>
                <td>DEF</td>
                <td>MDEF</td>
                <td>SPD</td>
                <td>物理決定力指数</td>
                <td>魔法決定力指数</td>
                <td>物理耐久力指数</td>
                <td>魔法耐久力指数</td>
            </tr>
            <tr>
                <td>{{object}}</td>
                <td>{{object.get_job_display}}</td>
                <td>{{object.hp}}</td>
                <td>{{object.atk}}</td>
                <td>{{object.matk}}</td>
                <td>{{object.dif}}</td>
                <td>{{object.mdif}}</td>
                <td>{{object.spd}}</td>
                <td>{{object.calcAtk}}</td>
                <td>{{object.calcMatk}}</td>
                <td>{{object.calcDif}}</td>
                <td>{{object.calcMdif}}</td>
            </tr>
        </table>
    </body>
</html>

kirara/templates/kirara/chara_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>kirara test</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <h1>キャラクターステータス一覧</h1>
        <table border="1">
            <tr>
                <td>キャラ</td>
                <td>クラス</td>
                <td>HP</td>
                <td>ATK</td>
                <td>MAT</td>
                <td>DEF</td>
                <td>MDEF</td>
                <td>SPD</td>
                <td>物理決定力指数</td>
                <td>魔法決定力指数</td>
                <td>物理耐久力指数</td>
                <td>魔法耐久力指数</td>
            </tr>
            {% for chara in object_list%}
            <tr>
                <td><a href="{% url 'chara_detail' pk=chara.id%}">{{chara}}</a></td>
                <td>{{chara.get_job_display}}</td>
                <td>{{chara.hp}}</td>
                <td>{{chara.atk}}</td>
                <td>{{chara.matk}}</td>
                <td>{{chara.dif}}</td>
                <td>{{chara.mdif}}</td>
                <td>{{chara.spd}}</td>
                <td>{{chara.calcAtk}}</td>
                <td>{{chara.calcMatk}}</td>
                <td>{{chara.calcDif}}</td>
                <td>{{chara.calcMdif}}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>